---
title: Stackbit Exto Theme
baseURL: "/"
params:
  color_scheme: dark
  accent_color: violet
  header:
    title: Wasim Abdalla
    has_nav: true
    logo_img: "/images/Wasim Abdalla..png"
  footer:
    content: ''
    links:
    - text: Made with love from Dallas, TX
      url: https://www.stackbit.com
      new_window: false
    has_social: true
disableKinds:
- RSS
